server:
  port: 8043

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:

      routes:
        - id: discovery-service
          uri: http://localhost:9091
          predicates:
            - Path=/
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: JwtAuthenticationFilter
#
#        - id: customer-service
#          uri: lb://CUSTOMER-SERVICE
#          predicates:
#            - Path=/api/v1/customers/**
#          filters:
#            - StripPrefix=2

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - Accept


management:
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: '*'
app:
  auth:
    jwtSecret: ${JWT_SECRET:secret}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}