server:
  port: 8043

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://products-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=2

ribbon:
  eureka:
    enabled: false

management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: '*'
