spring:
  application:
    name: api-gateway
server:
  port: 5555

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

zuul:
  routes:
    products:
      path: /products/**
      serviceId: products-service
