spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
server:
  port: 5555

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
       routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

ribbon:
  eureka:
    enabled: false

management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: '*'
