server:
  port: 8084

spring:
  application:
      name: auth-service
  cloud:
    openfeign:
      client:
        api:
          uri: ${USER_CLIENT:http://localhost:8086}
          name: user-service
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
app:
  auth:
    jwtSecret: ${JWT_SECRET:secret}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}