server:
  port: 8085

spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      validate-customer-fail: validate-customer-fail
      validate-customer-success: validate-customer-success
      orchestrator : orchestrator
    consumer:
      group-id: customer-group
      auto-offset-reset: latest

  data:
    mongodb:
      host: ${CUSTOMER_MONGO_DB_HOST:localhost}
      port: 27017
      username: ${CUSTOMER_MONGO_DB_USERNAME:admin}
      password: ${CUSTOMER_MONGO_DB_PASSWORD:wlg48cd8}
      authentication-database: admin
      auto-index-creation: true
      write-concern: NORMAL


logging:
  level:
    org:
      apache:
        kafka: OFF
