server:
  port: 8089

spring:

#  data:
#    mongodb:
#      host: ${SAFE_ROUTE_DB_HOST:localhost}
#      port: ${SAFE_ROUTE_DB_PORT:27017}
#      username: ${SAFE_ROUTE_DB_USERNAME:dev_admin}
#      password: ${SAFE_ROUTE_DB_PASSWORD:dev_982318}
#      authentication-database: admin
#      auto-index-creation: true
#      write-concern: NORMAL

logging:
  level:
    org:
      apache:
        kafka: OFF
